version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1 # For aws s3

x-env-node: &env-node
  docker:
    - image: cimg/python:3.10
  resource_class: small

jobs:
  test:
    <<: *env-node
    steps:
      - checkout
      # TODO: add tests
  deploy:
    <<: *env-node
    parameters:
      aws-role-arn:
        type: string
        description: AWS Role to assume via OIDC
      aws-region:
        type: env_var_name
        description: aws region override
        default: AWS_REGION
      aws-bucket-name:
        type: string
        description: EKS cluster to deploy
    environment:
      BUCKET_NAME: << parameters.aws-bucket-name >>
      AWS_REGION: us-east-2
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: << parameters.aws-role-arn >>
          # drop next line when https://github.com/CircleCI-Public/aws-cli-orb/issues/104 fixed
          role-session-name: circleci
          aws-region: << parameters.aws-region >>
      - run:
          name: Deploy for RDS PostgreSQL
          working_directory: "./rds-for-postgresql"
          command: ./deploy.sh "$BUCKET_NAME"
      - run:
          name: Deploy for Redshift
          working_directory: "./redshift"
          command: ./deploy.sh "$BUCKET_NAME"
workflows:
  test-deploy: # scheduled weekly on 'main' branch
    jobs:
      - test:
          context:
            - oidc
          name: test
          filters: &filter-always
            tags:
              only:
                - /^preview-.*/
                - /^staging-.*/
                - /^v.*/
                # - /^prod-block-.*/

      - deploy:
          context:
            - oidc
          requires:
            - test
          name: deploy chart on preview
          aws-role-arn: arn:aws:iam::672751098944:role/circleci-selectstar-cloudformation-templates
          aws-bucket-name: select-star-preview-cloudformation
          filters: &filter-preview
            tags:
              only: /^preview-.*/
            branches:
              ignore: /.*/


      - deploy:
          context:
            - oidc
          requires:
            - test
          name: deploy chart on staging
          aws-role-arn: arn:aws:iam::672751098944:role/circleci-selectstar-cloudformation-templates
          aws-bucket-name: select-star-staging-cloudformation
          filters: &filter-staging
            tags:
              only: /^staging-.*/
            branches:
              only: main

      - deploy:
          context:
            - oidc
          requires:
            - test
          name: deploy chart on production
          aws-role-arn: arn:aws:iam::672751098944:role/circleci-selectstar-cloudformation-templates
          aws-bucket-name: select-star-production-cloudformation
          filters: &filter-production
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
