name: "Deploy to S3"

on:
  workflow_call:
    inputs:
      aws-account-id:
        description: "AWS Account ID"
        type: string
        required: true
      aws-region:
        description: "AWS Region"
        type: string
        required: true
      aws-bucket-name:
        description: "AWS S3 bucket name"
        type: string
        required: true
      slack-job-name:
        required: false
        type: string
        description: Job name for notification
      slack-notify-success:
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
        description: URL for Slack webhook notification
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-${{ github.repository_owner }}-${{ github.event.repository.name }}
          role-session-name: "github-action"
          aws-region: ${{ inputs.aws-region }}
      - name: Deploy RDS for PostgreSQL
        working-directory: './rds-for-postgresql'
        run: ./deploy.sh "$BUCKET_NAME"
        env:
          BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      - name: Deploy Redshift
        working-directory: './redshift'
        run: ./deploy.sh "$BUCKET_NAME"
        env:
          BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      - name: Deploy Glue
        working-directory: './glue'
        run: ./deploy.sh "$BUCKET_NAME"
        env:
          BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      - name: Deploy Aurora
        working-directory: './aurora'
        run: ./deploy.sh "$BUCKET_NAME"
        env:
          BUCKET_NAME: ${{ inputs.aws-bucket-name }}
      - uses: 8398a7/action-slack@v3
        with:
          author_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          job_name: "${{ inputs.slack-job-name }}"
          status: ${{ job.status }}
          fields: ref,message,workflow,job,took,author
          mention: subteam^S03KPC0D63V # @devops
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: inputs.slack-job-name != '' && (failure() || (success() && inputs.slack-notify-success == true))
